name: CD

on:
  push:
    tags:
      - "v*.*.*" # ex: v1.0.0
  workflow_dispatch:

jobs:
  publish-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # necessário para ghcr
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version
        id: vars
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Orders.Api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/orders-api:latest
            ghcr.io/${{ github.repository_owner }}/orders-api:${{ steps.vars.outputs.VERSION }}

  # (Opcional) Deploy para ambiente (ex.: Azure Container Apps)
  # Adapte conforme sua cloud/alvo.
